name: PR
on:
  pull_request:
    branches:
      - master
jobs:
  test-build:
    runs-on: ubuntu-latest
    if: |
      ! contains(github.event.head_commit.message, '[skip ci]')
    steps:
      - uses: actions/checkout@v3
      - name: setup rust
        uses: hecrj/setup-rust-action@v1.4.1
        with:
          rust-version: stable
          components: clippy
      - name: lint
        run: |
          cargo clippy
      - name: test
        timeout-minutes: 5
        run: |
          # test everything except these two, to avoid flaky log_contains result
          cargo test -- --skip watchdog::test::test_watchdog --skip backlog::test::test_backlog
          # test them separately here
          cargo test -- watchdog::test::test_watchdog backlog::test::test_backlog
      - name: build-image
        run: |
          ./scripts/dockerbuild.sh
